<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510150347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create documents table with pgvector embedding column and HNSW cosine index';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');

        $this->addSql('CREATE TABLE documents (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            source VARCHAR(255) NOT NULL,
            chunk_index INT NOT NULL,
            content TEXT NOT NULL,
            embedding vector(1024) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY (id)
        )');

        // HNSW index for ANN search using cosine distance — matches the operator
        // we will use in /ask: `embedding <=> $queryVector`.
        $this->addSql('CREATE INDEX idx_documents_embedding ON documents USING hnsw (embedding vector_cosine_ops)');

        // Plain btree index to filter by source (e.g. delete + reingest one document).
        $this->addSql('CREATE INDEX idx_documents_source ON documents (source)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE documents');
    }
}
